# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Arty-A7-100-Master.xdc

# Block Designs: bd/mb1/mb1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1 || ORIG_REF_NAME==mb1} -quiet] -quiet

# IP: bd/mb1/ip/mb1_microblaze_0_0/mb1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_microblaze_0_0 || ORIG_REF_NAME==mb1_microblaze_0_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_dlmb_v10_0/mb1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_dlmb_v10_0 || ORIG_REF_NAME==mb1_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_ilmb_v10_0/mb1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_ilmb_v10_0 || ORIG_REF_NAME==mb1_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_dlmb_bram_if_cntlr_0/mb1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_ilmb_bram_if_cntlr_0/mb1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_lmb_bram_0/mb1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_lmb_bram_0 || ORIG_REF_NAME==mb1_lmb_bram_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_xbar_0/mb1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_xbar_0 || ORIG_REF_NAME==mb1_xbar_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_microblaze_0_axi_periph_0/mb1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_microblaze_0_axi_intc_0/mb1_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb1_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_microblaze_0_xlconcat_0/mb1_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb1_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_mdm_1_0/mb1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_mdm_1_0 || ORIG_REF_NAME==mb1_mdm_1_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_clk_wiz_1_0/mb1_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_clk_wiz_1_0 || ORIG_REF_NAME==mb1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_rst_clk_wiz_1_100M_0/mb1_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_axi_gpio_0_0/mb1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_axi_gpio_0_0 || ORIG_REF_NAME==mb1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_axi_uartlite_0_0/mb1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_axi_uartlite_0_0 || ORIG_REF_NAME==mb1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb1/ip/mb1_xlconstant_0_0/mb1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb1_xlconstant_0_0 || ORIG_REF_NAME==mb1_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Xilinx/Vivado/2021.1/myDev/project2/project2.gen/sources_1/bd/mb1/mb1_ooc.xdc
