# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/Vivado/2021.1/myDev/project2/project2.srcs/sources_1/bd/mb1/ip/mb1_dlmb_bram_if_cntlr_0/mb1_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'mb1_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/2021.1/myDev/project2/project2.gen/sources_1/bd/mb1/ip/mb1_dlmb_bram_if_cntlr_0/mb1_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb1_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Xilinx/Vivado/2021.1/myDev/project2/project2.srcs/sources_1/bd/mb1/ip/mb1_dlmb_bram_if_cntlr_0/mb1_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'mb1_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/2021.1/myDev/project2/project2.gen/sources_1/bd/mb1/ip/mb1_dlmb_bram_if_cntlr_0/mb1_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb1_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
